# Generated by Django 3.1 on 2020-09-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200909_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_1', models.CharField(blank=True, max_length=2)),
                ('ca_2', models.CharField(blank=True, max_length=2)),
                ('exam_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=3, null=True)),
                ('enroll_date', models.DateField()),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
