# Generated by Django 3.1 on 2020-09-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(through='users.Related', to='users.Subjects'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(through='users.Related', to='users.Subjects'),
        ),
    ]
